%% Script to automatically build the Simulink Model for Landslide EWS
model_name = 'lews_model';

% Close if already open
if bdIsLoaded(model_name)
    close_system(model_name, 0);
end

% Create new system
new_system(model_name);
open_system(model_name);

% Set simulation parameters (Stop time = 7200s, Solver = ode45 or FixedStep)
set_param(model_name, 'StopTime', '7200', 'Solver', 'VariableStepAuto');

% 1. Add Input Blocks (From Workspace)
add_block('simulink/Sources/From Workspace', [model_name '/Rain_Sensor'], ...
    'VariableName', 'rain_input', 'Position', [50, 60, 150, 90]);

add_block('simulink/Sources/From Workspace', [model_name '/Moisture_Sensor'], ...
    'VariableName', 'moist_input', 'Position', [50, 150, 150, 180]);

add_block('simulink/Sources/From Workspace', [model_name '/Tilt_Sensor'], ...
    'VariableName', 'tilt_input', 'Position', [50, 260, 150, 290]);

% 2. Tilt Rate Computation: Derivative -> Abs -> Gain (deg/s to deg/hr: * 3600)
add_block('simulink/Continuous/Derivative', [model_name '/Tilt_Derivative'], ...
    'Position', [200, 260, 240, 290]);

add_block('simulink/Math Operations/Abs', [model_name '/Abs'], ...
    'Position', [270, 265, 300, 285]);

add_block('simulink/Math Operations/Gain', [model_name '/To_deg_per_hr'], ...
    'Gain', '3600', 'Position', [330, 260, 380, 290]);

% 3. Physics Block: MATLAB Function for Factor of Safety (FoS)
phys_blk = [model_name '/Physics_FoS_Model'];
add_block('simulink/User-Defined Functions/MATLAB Function', phys_blk, ...
    'Position', [250, 95, 370, 155]);

phys_doc = sprintf(['function FoS = Physics_FoS_Model(rain, moist)\n' ...
    '%% Slope and Geotechnical Constants\n' ...
    'c_prime = 12;     %% kPa\n' ...
    'phi_rad = deg2rad(30);\n' ...
    'beta_rad = deg2rad(35);\n' ...
    'gamma_s = 18;     %% kN/m^3\n' ...
    'gamma_w = 9.81;   %% kN/m^3\n' ...
    'z = 1.5;          %% meters\n' ...
    '\n' ...
    '%% Pore pressure estimation\n' ...
    'theta_crit = 0.35;\n' ...
    'if moist > theta_crit\n' ...
    '    u = gamma_w * (moist - theta_crit) * z * 2.5 + (rain * 0.02);\n' ...
    'else\n' ...
    '    u = 0;\n' ...
    'end\n' ...
    '\n' ...
    'normal_stress = gamma_s * z * (cos(beta_rad))^2;\n' ...
    'eff_stress = max(normal_stress - u, 0.1);\n' ...
    'resisting_shear = c_prime + eff_stress * tan(phi_rad);\n' ...
    'driving_shear = gamma_s * z * sin(beta_rad) * cos(beta_rad);\n' ...
    'FoS = resisting_shear / max(driving_shear, 0.001);\n' ...
    'end\n']);

sf = sfroot;
chart = sf.find('Path', phys_blk, '-isa', 'Stateflow.EMChart');
if ~isempty(chart)
    chart.Script = phys_doc;
end

% 4. Intelligent Risk Assessment Block (MATLAB Function)
ai_blk = [model_name '/Intelligent_Alert_Engine'];
add_block('simulink/User-Defined Functions/MATLAB Function', ai_blk, ...
    'Position', [450, 140, 580, 230]);

ai_doc = sprintf(['function [AlertLevel, RiskPct] = Intelligent_Alert_Engine(FoS, moist, rain, tilt_rate)\n' ...
    '%% Persistent variable to handle alert state and avoid flickering\n' ...
    'persistent current_state;\n' ...
    'if isempty(current_state)\n' ...
    '    current_state = 0;\n' ...
    'end\n' ...
    '\n' ...
    '%% Continuous Risk Percentage calculation (0 to 100%%)\n' ...
    'fos_risk = max(0, min(100, (1.8 - FoS) * 100));\n' ...
    'kinematic_risk = min(100, tilt_rate * 20);\n' ...
    'moist_risk = max(0, (moist - 0.25) * 250);\n' ...
    'RiskPct = max(0, min(100, 0.4*fos_risk + 0.35*kinematic_risk + 0.25*moist_risk));\n' ...
    '\n' ...
    '%% Multi-tier Warning Levels with Hysteresis:\n' ...
    '%% 0 = Green (Safe), 1 = Yellow (Advisory), 2 = Red (Evacuate)\n' ...
    'if current_state == 0\n' ...
    '    if RiskPct >= 50 || FoS < 1.15 || tilt_rate > 3.0\n' ...
    '        current_state = 1;\n' ...
    '    end\n' ...
    'elseif current_state == 1\n' ...
    '    if RiskPct >= 80 || FoS < 1.0 || (FoS < 1.1 && tilt_rate > 2.0)\n' ...
    '        current_state = 2;\n' ...
    '    elseif RiskPct < 35 && FoS > 1.3 && tilt_rate < 1.0\n' ...
    '        current_state = 0;\n' ...
    '    end\n' ...
    'elseif current_state == 2\n' ...
    '    if RiskPct < 60 && FoS > 1.25\n' ...
    '        current_state = 1;\n' ...
    '    end\n' ...
    'end\n' ...
    'AlertLevel = current_state;\n' ...
    'end\n']);

chart2 = sf.find('Path', ai_blk, '-isa', 'Stateflow.EMChart');
if ~isempty(chart2)
    chart2.Script = ai_doc;
end

% 5. Add Scopes and Displays
add_block('simulink/Sinks/Scope', [model_name '/EWS_Dashboard_Scope'], ...
    'NumInputPorts', '4', 'Position', [670, 95, 730, 245]);

add_block('simulink/Sinks/Display', [model_name '/Alert_Level_Display'], ...
    'Position', [670, 260, 750, 290]);

% 6. Connect Lines
add_line(model_name, 'Rain_Sensor/1', 'Physics_FoS_Model/1', 'autorouting', 'on');
add_line(model_name, 'Moisture_Sensor/1', 'Physics_FoS_Model/2', 'autorouting', 'on');

add_line(model_name, 'Tilt_Sensor/1', 'Tilt_Derivative/1', 'autorouting', 'on');
add_line(model_name, 'Tilt_Derivative/1', 'Abs/1', 'autorouting', 'on');
add_line(model_name, 'Abs/1', 'To_deg_per_hr/1', 'autorouting', 'on');

add_line(model_name, 'Physics_FoS_Model/1', 'Intelligent_Alert_Engine/1', 'autorouting', 'on');
add_line(model_name, 'Moisture_Sensor/1', 'Intelligent_Alert_Engine/2', 'autorouting', 'on');
add_line(model_name, 'Rain_Sensor/1', 'Intelligent_Alert_Engine/3', 'autorouting', 'on');
add_line(model_name, 'To_deg_per_hr/1', 'Intelligent_Alert_Engine/4', 'autorouting', 'on');

% Connect to Dashboard Scope
% Port 1: Rain & Moisture (Muxed)
add_block('simulink/Signal Routing/Mux', [model_name '/Mux_Inputs'], ...
    'Inputs', '2', 'Position', [450, 50, 455, 85]);
add_line(model_name, 'Rain_Sensor/1', 'Mux_Inputs/1', 'autorouting', 'on');
add_line(model_name, 'Moisture_Sensor/1', 'Mux_Inputs/2', 'autorouting', 'on');
add_line(model_name, 'Mux_Inputs/1', 'EWS_Dashboard_Scope/1', 'autorouting', 'on');

% Port 2: Factor of Safety
add_line(model_name, 'Physics_FoS_Model/1', 'EWS_Dashboard_Scope/2', 'autorouting', 'on');

% Port 3: Risk Percentage
add_line(model_name, 'Intelligent_Alert_Engine/2', 'EWS_Dashboard_Scope/3', 'autorouting', 'on');

% Port 4: Alert Level (0 = Green, 1 = Yellow, 2 = Red)
add_line(model_name, 'Intelligent_Alert_Engine/1', 'EWS_Dashboard_Scope/4', 'autorouting', 'on');

% Connect to Display
add_line(model_name, 'Intelligent_Alert_Engine/1', 'Alert_Level_Display/1', 'autorouting', 'on');

% Save model
save_system(model_name);
disp('Simulink model lews_model.slx created and wired successfully!');
